# Generated by Django 6.1 on 2026-09-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_populate_job_execution_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2000)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('scope_hash', models.CharField(max_length=64, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(default='in-progress', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_content_type', models.CharField(blank=True, max_length=100)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'idempotency key',
                'verbose_name_plural': 'idempotency keys',
                'indexes': [models.Index(fields=['status', 'created'], name='core_idempo_status_f79a08_idx')],
            },
        ),
    ]
